permalink: /:year:month:day/:title
url: hakolyhak.org

# variables
name: HakOlyHak
description: The best information security/hacking/computer security meetup around!
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true